config/routes.rb
Firehoseapp::Application.routes.draw do

   root 'static_pages#index'

   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index

		@pics = Pic.all

	end

	def new
		
		@pic = Pic.new

	end

	# This executes code for save button operation
	def create
		Pic.create( pic_params)
		redirect_to pics_path

	end

	private

	def pic_params
		params.require(:pic).permit(:lesson, :emotion, :learned)

	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firehoseapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
   
    <%= link_to 'Firehose App', root_path, :class => 'brand' %>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
    
    <ul class="nav">
    	<li>
    		<%= link_to 'Add a Picture', new_pic_path %>
    	</li>
    	<li>
    		<%= link_to 'Picture Display', pics_path %>
    	</li>
    </ul>


    </div>
     
    </div>
    </div>
    </div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="fishbox  span4 text-center">
		<h1 class="custom-h1">
			Lesson: <%= pic.lesson %>
		</h1>
			<br/>
		<h2>
			<br/>
			Emotion: <%= pic.emotion %>
			<br/>
			Learned: <%= pic.learned %>
		</h2>
	</div>
<% end %>

app/views/pics/new.html.erb
<div class="fishbox">
	<h2>
		Submit Your Pic

		<%= simple_form_for @pic do |f| %>

			<%= f.input :lesson %>
			<%= f.input :emotion %>
			<%= f.input :learned %>

			<%= f.button :submit, 'Save' %>
		<% end %>
	</h2>

</div>

app/views/static_pages/index.html.erb
<div class="fishbox span8 offset3 text-center">


	<h1 class="custom-h1">Hi I'm Marco</h1>

	<br/>

	<h2>This is my awesome web development journey</h2>


	<br/>

	<!-- Ruby Code -->
	<%= link_to 'Launch', pics_path, :class => 'btn-large btn btn-warning' %>

</div>